// Ang3/src/app/favorite-links/favorite-links.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'favorite-links',
  templateUrl: 'favorite-links.component.html',
  styleUrls: ['favorite-links.component.css']
})
export class FavoriteLinksComponent {
  favoriteLinks = [
    { name: 'Google', url: 'https://www.google.com', color: 'blue' },
    { name: 'GitHub', url: 'https://www.github.com', color: 'blue' },
    { name: 'Angular', url: 'https://angular.io', color: 'blue' },
  ];

  selectedLinkIndex: number = -1;

  selectLink(index: number) {
    this.selectedLinkIndex = index;
  }
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div>
        <ul>
          <li *ngFor="let link of favoriteLinks; let i = index">
            <a [href]="link.url" [style.color]="i === selectedLinkIndex ? 'red' : 'blue'" (click)="selectLink(i)">{{ link.name }}</a>
          </li>
        </ul>
      </div>
      
</body>
</html>

// lab4/src/components/favoriteLinks/FavoriteLinks.tsx
import React, { useState } from 'react'
import './FavoriteLinks.css'

type Link = {
    id: number;
    name: string;
    url: string;
}

const favoriteLinks: Link[] = [
    { id: 1, name: 'Google', url: 'https://www.google.com' },
    { id: 2, name: 'GitHub', url: 'https://www.github.com' },
    { id: 3, name: 'React', url: 'https://reactjs.org' },
];

const FavoriteLinks: React.FC = () => {

    const [selectedLinkId, setSelectedLinkId] = useState<number | null>(null);

    const handleLinkClick = (linkId: number) => {
        if (selectedLinkId === linkId) {
            setSelectedLinkId(null);
        } else {
            setSelectedLinkId(linkId);
        }
    };

    return (
        <div className="favorite-links">
            <header className="favorite-links__header">
                <ul>
                    {favoriteLinks.map(link => (
                        <li
                            key={link.id}
                            onClick={() => handleLinkClick(link.id)}
                            className={selectedLinkId === link.id ? 'selected-link' : ''}
                        >
                            <a href={link.url}>
                                {link.name}
                            </a>
                        </li>
                    ))}
                </ul>
            </header>
        </div>
    );
};
export default FavoriteLinks;
